{
 "title": "Nginx Basic",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "RPS Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance)(rate(nginx_response_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS By Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by(instance)(rate(nginx_response_total{status=~\"2..\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "3xx rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by(instance)(rate(nginx_response_total{status=~\"3..\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4xx rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by(instance)(rate(nginx_response_total{status=~\"4..\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "5xx rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum by(instance)(rate(nginx_response_total{status=~\"5..\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Responce heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(nginx_response_time_bucket[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "User Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(agent)(rate(nginx_response_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}