{
 "title": "Nginx RPS",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(nginx_response_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(nginx_response_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "method",
    "label": "Method:",
    "query": {
     "query": "label_values(nginx_response_total{job=~\"$job\", instance=~\"$instance\"},method)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol:",
    "query": {
     "query": "label_values(nginx_response_total{job=~\"$job\", instance=~\"$instance\"},protocol)"
    }
   },
   {
    "name": "status",
    "label": "Status:",
    "query": {
     "query": "label_values(nginx_response_total{job=~\"$job\", instance=~\"$instance\"},status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance)(rate(nginx_response_total{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", protocol=~\"$protocol\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responce heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_response_time_bucket{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", protocol=~\"$protocol\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(agent)(rate(nginx_response_total{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", protocol=~\"$protocol\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}